"""Train a tiny value network; PyTorch is required only for this offline step."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile

import numpy as np
import torch


ROOT = Path(__file__).resolve().parents[1]
FEATURES = 160
DEFAULT_HIDDEN = 16
TARGETS = {"margin": FEATURES, "win": FEATURES + 1}
DATA_ID = hashlib.sha256(b"".join(
    (ROOT / name).read_bytes() for name in (
        "scripts/generate-nn-data.cpp", "cpp/neural-policy.hpp",
        "cpp/rollout-policy.hpp", "cpp/rollout-weights.hpp", "cpp/mcts.hpp",
        "cpp/jaipur_ai.cpp"
    )
)).hexdigest()[:12]


class ValueNet(torch.nn.Module):
    def __init__(self, baseline_weights, hidden):
        super().__init__()
        self.register_buffer("baseline", torch.tensor(baseline_weights, dtype=torch.float32))
        self.hidden = torch.nn.Linear(FEATURES, hidden)
        self.value = torch.nn.Linear(hidden, 1)
        torch.nn.init.zeros_(self.value.weight)
        torch.nn.init.zeros_(self.value.bias)

    def forward(self, x):
        baseline = x @ self.baseline
        correction = self.value(torch.relu(self.hidden(x))).squeeze(-1)
        return torch.tanh(baseline + correction).unsqueeze(-1)


class SymmetricValueNet(torch.nn.Module):
    """Odd in player-specific features, with public-state interactions."""
    def __init__(self, baseline_weights, hidden):
        super().__init__()
        self.register_buffer("baseline", torch.tensor(baseline_weights, dtype=torch.float32))
        self.signed = torch.nn.Linear(141, hidden, bias=False)
        self.public = torch.nn.Linear(18, hidden)
        self.value = torch.nn.Linear(hidden, 1, bias=False)
        torch.nn.init.zeros_(self.value.weight)

    def forward(self, x):
        signed = torch.cat((x[:, :140], x[:, 157:158]), dim=1)
        public = torch.cat((x[:, 140:157], x[:, 158:159] + x[:, 159:160]), dim=1)
        difference = self.signed(signed)
        context = self.public(public)
        correction = self.value(torch.relu(context + difference) -
                                torch.relu(context - difference)).squeeze(-1)
        return torch.tanh(x @ self.baseline + correction).unsqueeze(-1)


def data_file(binary: Path, directory: Path, games: int, seed: int):
    path = directory / f"positions-{DATA_ID}-{games}-{seed}.f32"
    if not path.exists():
        temporary = path.with_suffix(".partial")
        with temporary.open("wb") as output:
            subprocess.run([str(binary), str(games), str(seed)], stdout=output, check=True)
        temporary.replace(path)
    data = np.fromfile(path, dtype="<f4")
    if data.size % (FEATURES + 2):
        raise ValueError(f"Incomplete training record: {path}")
    return data.reshape(-1, FEATURES + 2)


def values(values):
    def literal(value):
        number = f"{float(value):.9g}"
        if "." not in number and "e" not in number:
            number += ".0"
        return number + "f"
    return ",\n".join(literal(value) for value in values)


def export_header(model, path: Path, metadata):
    tensors = [("NN_BASELINE", model.baseline.detach().numpy())]
    if isinstance(model, SymmetricValueNet):
        tensors += [
            ("NN_W_DIFF", model.signed.weight.detach().T.reshape(-1).numpy()),
            ("NN_W_PUBLIC", model.public.weight.detach().T.reshape(-1).numpy()),
            ("NN_B_PUBLIC", model.public.bias.detach().numpy()),
            ("NN_W2", model.value.weight.detach().reshape(-1).numpy()),
        ]
    else:
        tensors += [
            ("NN_W1", model.hidden.weight.detach().reshape(-1).numpy()),
            ("NN_B1", model.hidden.bias.detach().numpy()),
            ("NN_W2", model.value.weight.detach().reshape(-1).numpy()),
            ("NN_B2", model.value.bias.detach().numpy()),
        ]
    lines = ["// Generated by scripts/train-neural.py; see training metadata beside this file.",
             f"constexpr int NN_HIDDEN = {metadata['hidden_units']};"]
    if isinstance(model, SymmetricValueNet):
        lines.append("#define NN_SYMMETRIC 1")
        lines.append("#define NN_TRANSPOSED 1")
    for name, weights in tensors:
        lines.append(f"constexpr std::array<float, {weights.size}> {name} = {{\n{values(weights)}\n}};")
    path.write_text("\n".join(lines) + "\n")
    metadata["weights_sha256"] = hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--generator", type=Path, required=True)
    parser.add_argument("--directory", type=Path,
                        default=Path(tempfile.gettempdir()) / "jaipur-nn-training")
    parser.add_argument("--train-games", type=int, default=12000)
    parser.add_argument("--validation-games", type=int, default=2000)
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--batch-size", type=int, default=4096)
    parser.add_argument("--target", choices=TARGETS, default="margin")
    parser.add_argument("--architecture", choices=("residual", "symmetric"), default="residual")
    parser.add_argument("--hidden", type=int, default=DEFAULT_HIDDEN)
    args = parser.parse_args()
    if not 1 <= args.hidden <= 64:
        parser.error("--hidden must be in [1, 64]")
    args.directory.mkdir(parents=True, exist_ok=True)
    torch.manual_seed(20260923)
    np.random.seed(20260923)
    torch.set_num_threads(min(4, os.cpu_count() or 1))
    train = data_file(args.generator, args.directory, args.train_games, 20260923)
    validation = data_file(args.generator, args.directory, args.validation_games, 20260924)
    x = torch.from_numpy(train[:, :FEATURES].copy())
    target = TARGETS[args.target]
    y = torch.from_numpy(train[:, target:target + 1].copy())
    val_x = torch.from_numpy(validation[:, :FEATURES].copy())
    val_y = torch.from_numpy(validation[:, target:target + 1].copy())
    baseline_text = (ROOT / "cpp/rollout-weights.hpp").read_text()
    body = baseline_text.split("{", 1)[1].split("}", 1)[0]
    baseline_weights = np.pad(np.fromstring(body.replace("\n", ""), sep=","),
                              (0, FEATURES - 140))
    if args.target == "win":
        baseline_weights *= 4
    baseline = np.tanh(validation[:, :FEATURES] @ baseline_weights)
    baseline_mse = float(np.mean((baseline - validation[:, target]) ** 2))
    print(f"data: train={len(train)} validation={len(validation)} baseline_mse={baseline_mse:.6f}", flush=True)
    model_type = SymmetricValueNet if args.architecture == "symmetric" else ValueNet
    model = model_type(baseline_weights, args.hidden)
    optimizer = torch.optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-5)
    best = float("inf")
    best_state = None
    stale = 0
    for epoch in range(args.epochs):
        model.train()
        order = torch.randperm(len(x))
        for indices in order.split(args.batch_size):
            batch_x = x[indices].clone()
            batch_y = y[indices].clone()
            # Player swap: differential features change sign; public market,
            # deck and token features remain fixed; hand sizes trade places.
            flipped = torch.rand(len(indices)) < 0.5
            batch_x[flipped, :140] *= -1
            batch_x[flipped, 157] *= -1
            own = batch_x[flipped, 158].clone()
            batch_x[flipped, 158] = batch_x[flipped, 159]
            batch_x[flipped, 159] = own
            batch_y[flipped] *= -1
            prediction = model(batch_x)
            loss = torch.nn.functional.mse_loss(prediction, batch_y)
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()
        model.eval()
        with torch.no_grad():
            val_mse = float(torch.nn.functional.mse_loss(model(val_x), val_y))
        print(f"epoch={epoch + 1} validation_mse={val_mse:.6f}", flush=True)
        if val_mse < best - 1e-7:
            best = val_mse
            best_state = {key: value.detach().clone() for key, value in model.state_dict().items()}
            stale = 0
        else:
            stale += 1
            if stale == 12:
                break
    model.load_state_dict(best_state)
    metadata = {"target": args.target, "train_games": args.train_games, "validation_games": args.validation_games,
                "train_positions": len(train), "validation_positions": len(validation),
                "baseline_validation_mse": baseline_mse, "neural_validation_mse": best,
                "seed_train": 20260923, "seed_validation": 20260924,
                "architecture": args.architecture, "hidden_units": args.hidden,
                "data_id": DATA_ID}
    export_header(model, args.directory / "nn-weights.hpp", metadata)
    (args.directory / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
    print(json.dumps(metadata, indent=2), flush=True)


if __name__ == "__main__":
    main()
